import type { Metadata } from "next";
import { cookies } from "next/headers";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Portfolio | James Kent",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
	const cookieStore = await cookies();
	const theme = cookieStore.get("theme")?.value as "light" | "dark" | undefined;
	const htmlClass = theme === "dark" ? "dark" : theme === "light" ? "light" : "";
	return (
		<html lang="en" className={htmlClass} suppressHydrationWarning>
			<head>
				<meta name="color-scheme" content="dark light" />
			</head>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
